services:
  mcp_massive:
    build: .
    volumes:
      - .:/app
    container_name: mcp_massive_server
    environment:
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    stdin_open: true
    tty: true
